# Config file for Air hot-reload
[build]
cmd = "go build -o ./bin/beacon"
bin = "beacon"
full_bin = "./bin/beacon"
watch_dir = "."
exclude_dir = ["db", "vendor", "templates"]
delve = false
log = "air_errors.log"
