services:
  beacon:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088" # web GUI + API
    volumes:
      - ./beacon.yaml:/app/beacon.yaml # config file
      - ./beacon.db:/app/beacon.db # persist DB
