services:
  beacon:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088" # web GUI + API
    volumes:
      - ./config.sample.yaml:/root/beacon.yaml # config file
      # Uncomment following line to persist DB
      # - ./beacon.db:/root/beacon.db
