services:
  beacon-github:
    url: "https://github.com/davidmasek/beacon"
    status:
      - 200
    content:
      - Beacon
  beacon-periodic-checker:
  example-with-extras:
    timeout: 48h
  example-basic-web:
    url: "https://httpbin.org/get"
  example-temp-disable:
    url: "will-not-be-used-because-disabled"
    enabled: false


email:
  smtp_server: mail.smtp2go.com
  smtp_port: 587
  smtp_username: beacon
  smtp_password:
  send_to: you@example.fake
  sender: noreply@example.fake
  prefix: "[dev]"
  # defaults to sending email
  enabled: false

# examples: UTC, Australia/Sydney, America/Chicago
timezone: "Europe/Prague"
# 17 == 5pm, and so on
report_time: 17
