websites:
  beacon-github:
      url: "https://github.com/davidmasek/beacon"
      status:
        - 200
      content:
        - Beacon

heartbeats:
  heartbeat-listener:
      timeout: 24h

email:
  smtp_server: mail.smtp2go.com
  smtp_port: 587
  smtp_username: beacon
  smtp_password:
  send_to: beacon@optimisticotter.com
  sender: noreply@optimisticotter.com
  prefix: "[dev]"
