services:
  beacon-github:
    url: "https://github.com/davidmasek/beacon"
    status:
      - 200
    content:
      - Beacon
  beacon-periodic-checker:
  example-basic-web:
    url: "https://httpbin.org/get"
  example-temp-disable:
    url: "will-not-be-used-because-disabled"
    enabled: false


email:
  smtp_server: smtp4dev
  smtp_port: 25
  smtp_username: beacon
  smtp_password: beacon
  send_to: you@example.fake
  sender: noreply@example.fake
  prefix: "[beacon-example]"
  # defaults to sending email
  enabled: true

# examples: UTC, Australia/Sydney, America/Chicago
timezone: "Europe/Prague"
# 17 == 5pm, and so on
report_time: 17
