websites:
  beacon-github:
      url: "https://github.com/davidmasek/beacon"
      status:
        - 200
      content:
        - Beacon

email:
  smtp_server: mail.smtp2go.com
  smtp_port: 587
  smtp_username: beacon
  smtp_password:
  send_to: you@example.fake
  sender: noreply@example.fake
  prefix: "[dev]"
